#开发环境
server:
 port: 8080
 servlet:
  context-path: /

spring:
 datasource:
  dynamic: #多数据源配置
   primary: master  #默认数据源
   datasource:
    master: #主数据源
     url: jdbc:mysql://localhost:3306/clouddisk?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
     driver-class-name: com.mysql.cj.jdbc.Driver
     username: root
     password: 123456
    quartz: #Quartz数据源
     url: jdbc:mysql://localhost:3306/clouddisk_quartz?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
     driver-class-name: com.mysql.cj.jdbc.Driver
     username: root
     password: 123456

#项目配置
project:
 redis: #Redis配置
  host: 47.102.202.189
  #password:
  port: 6379
  database: 0
  ssl: false
  timeout: 10000 #连接超时时间
  maxIdle: 20 #最大空闲时间
  maxTotal: 40 #最大连接数
  maxWait: 10000 #最大等待时间
  testOnBorrow: true #借用jedis实例
