#生产环境

#Tomcat服务器配置
server: 
 port: 8080
 contextPath: /

spring:
 datasource:
  dynamic: #多数据源配置
   primary: master  #默认数据源
   datasource:
    master: #主数据源
     url: jdbc:mysql://39.108.122.170:3306/db_yan_clouddisk?useUnicode=true&useSSL=false&characterEncoding=utf8
     driver-class-name: com.mysql.jdbc.Driver
     username: root
     password: 123456
    quartz: #Quartz数据源
     url: jdbc:mysql://39.108.122.170:3306/db_yan_quartz?characterEncoding=utf-8
     driver-class-name: com.mysql.jdbc.Driver
     username: root
     password: 123456


#项目配置
project: 
 redis: 
  host: 127.0.0.1
  password: 980503
  port: 6379
  database: 0
  ssl: false
  timeout: 10000 #连接超时时间
  maxIdle: 20 #最大空闲时间
  maxTotal: 40 #最大连接数
  maxWait: 10000 #最大等待时间
  testOnBorrow: true #借用jedis实例